name = input("who are you?")
city = input('where do you live?')
age = input('how old are you?')
hobby = input('what is faourite hobby?')
movie = input ('what is your favourite movie?')
food = input('what is your favourite food?')

print("------your details filled by you-----")
print("name", name)
print("city", city)
print("age ", age)
print("hobby", hobby)
print("movie" , movie)
print("food", food)